### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/kamon-akka#2]

**Comment by cory-p-oncota** [comment]
[This line](https://github.com/kamon-io/kamon-akka/blob/master/kamon-akka-2.4.x/src/main/scala/kamon/akka/instrumentation/ActorInstrumentation.scala#L77) has been a big pain point in particular. 

Incompatibilities between 2.11 and 2.12 reflection mean 2.11 is expecting `akka$actor$UnstartedCell$$queue` while 2.12 only requires `queue`. Otherwise, I've been able to get a stable build [here](https://github.com/cotalabs/kamon-akka/tree/2.12).

**Comment by dpsoft** [comment]
@cory-p-oncota PR?

**Comment by agarbutt** [comment]
@dpsoft @cory-p-oncota, I believe this issue is blocked on getting an acceptable release (0.6.5) from the kamon-scala library, correct?

**Comment by cory-p-oncota** [comment]
That's correct

**Comment by cory-p-oncota** [comment]
Updates on my branch now test and publish without any command line massaging but I'm really not too fond of [the solution](https://github.com/cotalabs/kamon-akka/blob/2.12/kamon-akka-2.4.x/src/main/scala/kamon/akka/instrumentation/ActorInstrumentation.scala#L79).

**Comment by dpsoft** [comment]
@cory-p-oncota @agarbutt  I've just release the version 0.6.5 of `kamon-scala` ;)

**Comment by cory-p-oncota** [comment]
Currently blocked by https://github.com/sbt/sbt-aspectj/pull/30, so usage under 2.12 will also depend on the next `sbt-aspectj` release.

When publishing all dependencies locally though, things are looking good downstream testing against some of our services.

**Comment by andrebeat** [comment]
@cory-p-oncota Since that has already been merged, should we ask [sbt-aspectj](https://github.com/sbt/sbt-aspectj) to release a new version?

**Comment by cory-p-oncota** [comment]
My follow up has been a bit poor on this after coming back from holiday. I've created an issue in sbt-aspectj requesting the release.

**Comment by everylifetechnologies** [comment]
What is the current status of the 2.12 distribution?

**Comment by ivantopo** [comment]
hey @everylifetechnologies! we already published in our bintray repo (https://bintray.com/kamon-io/releases), waiting for sync with central so that we can announce it, but 0.6.5 is already out :)

**Comment by everylifetechnologies** [comment]
@ivantopo fantastic !

**Comment by everylifetechnologies** [comment]
@ivantopo Are we still waiting on sync or is there a reason it isn't in central yet?

**Comment by ivantopo** [comment]
we are still having some issues with the sync process :(... will update when it is ready
