### ISSUE TITLE
Repository description is a dead link

### ISSUE THREAD

**Issue by ollyw** [kamon-io/kamon-akka#51]
The github repository description at the top of the page points to a dead link. Perhaps it should point to https://kamon.io/docs/latest/instrumentation/akka/ ? I can't put in a PR to fix this, as it is a Github specific description AFAIK

**Comment by ivantopo** [comment]
Thanks a lot @ollyw, fixed it just now!

**Comment by ollyw** [comment]
That was super quick. Thanks!
