### ISSUE TITLE
Support for Artery

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-akka#58]

**Comment by danischroeter** [comment]
Hi @tPl0ch did you get time to look into this topic or any progress? Do you need some help?

Added the context from gitter for reference...
@tPl0ch:
> @ivantopo If you can point me to the relevant parts of the code I could try making a PR happen :)

@ivantopo
> awesome! the interesting stuff for context propagation on remote is in two places:
the definition of what needs to be changed: https://github.com/kamon-io/kamon-akka/blob/master/kamon-akka/src/main/scala/kamon/instrumentation/akka/remote/RemotingInstrumentation.scala#L16-L50 the advices/interceptors mentioned there, which are the ones actually doing the work
I would have thought that the AkkaPduProtobufCodec instrumentation would have been enough, unless the Artery implementation uses a different way of packaging the messages before being sent
the first thing would be figuring out what's the difference between the sequence of events for sending a message with the netty transport vs artery and then probably just reuse some of the logic we already have there
it might be that either the code path just goes on a completely different direction, or that it just detours in some parts and the Context is being lost
it will be hard, but it will be fun!

**Comment by juanavelez** [comment]
Interested to know if there is any traction on this effort as well.

**Comment by danischroeter** [comment]
@ivantopo thanks!
