### ISSUE TITLE
instrument AkkaForkJoinPool

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/kamon-akka#7]
I've been using kamon-akka to get metrics from an application and have found that the existing ForkJoinPool metrics don't provide much detail about the load being handled by the ForkJoinPools. The queued-task-count rarely goes above zero. I've also been outputting the queued-submission-count from the ForkJoinPool and it takes a massive amount of load to make this go above zero.
I'm wondering if it would be useful to use instrument AkkaForkJoinPool to try to get counts the ```execute``` calls.
I'm not sure how but it would be useful if the AkkaForkJoinPool metrics were tied back to the dispatcher that wraps the AkkaForkJoinPool.

**Comment by ivantopo** [comment]
hey @pjfanning! In theory, if those numbers never go above zero that's good news, as your pool always has some available thread to process anything that gets submitted to it, unless you have some long running operations that might hog some threads or a huge amount of tasks, this value should always remain low... also, when you say that queued-submission-count and queued-task-count rarely go above zero, what value are you looking at? max?

I see the value in counting the executed tasks in a thread pool, regardless of it being the AkkaForkJoinPool, we might add that soon, thanks for the suggestion!
